services:
  pg1:
    build:
      context: ./services/postgres/
      dockerfile: Dockerfile
    
    container_name: pg1
    
    environment:
      POSTGRES_USER: jfp
      POSTGRES_PASSWORD: jfp
      POSTGRES_DB: shorturl
    
    restart: always
  
  pg2:
    build:
      context: ./services/postgres/
      dockerfile: Dockerfile
    
    container_name: pg2
    
    environment:
      POSTGRES_USER: jfp
      POSTGRES_PASSWORD: jfp
      POSTGRES_DB: shorturl
    
    restart: always

  url-encoder:
    build:
      context: ./services/url_encoder/
      dockerfile: Dockerfile
    
    container_name: url-encoder
    
    environment:
      - CONN_STRINGS=postgresql://jfp:jfp@pg1:5432/shorturl
      - CONN_STRINGS=postgresql://jfp:jfp@pg2:5432/shorturl
      - PYTHONUNBUFFERED=1

    depends_on:
      - pg1
      - pg2

    restart: always

  api:
    build:
      context: ./services/api/
      dockerfile: Dockerfile
    
    container_name: api

    environment:
      - CONN_STRINGS=postgresql://jfp:jfp@pg:5432/shorturl
      - CONN_STRINGS=postgresql://jfp:jfp@pg2:5432/shorturl
      - PYTHONUNBUFFERED=1
    
    depends_on:
      - "url-encoder"
      
    restart: always